// utils/auditActions.js
export const ACTIONS = {
  TESTIMONIAL_APPROVED: 'TESTIMONIAL_APPROVED',
  TESTIMONIAL_DELETED: 'TESTIMONIAL_DELETED',

  BOOKING_STATUS_CHANGED: 'BOOKING_STATUS_CHANGED',

  USER_ROLE_CHANGED: 'USER_ROLE_CHANGED',
  USER_STATUS_CHANGED: 'USER_STATUS_CHANGED',

  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRODUCT_DELETED: 'PRODUCT_DELETED',

  COURSE_CREATED: 'COURSE_CREATED',
  COURSE_UPDATED: 'COURSE_UPDATED',
  COURSE_DELETED: 'COURSE_DELETED',

  WORKSHOP_CREATED: 'WORKSHOP_CREATED',
  WORKSHOP_UPDATED: 'WORKSHOP_UPDATED',
  WORKSHOP_DELETED: 'WORKSHOP_DELETED',
};
